# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-09 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QQlean', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='phone',
            field=models.CharField(max_length=200, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='summ_bath',
            field=models.CharField(default=b'', max_length=200, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd1\x81\xd0\xb0\xd1\x83\xd0\xb7\xd0\xbb\xd0\xbe\xd0\xb2'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='summ_room',
            field=models.CharField(default=b'', max_length=200, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xba\xd0\xbe\xd0\xbc\xd0\xbd\xd0\xb0\xd1\x82'),
        ),
        migrations.AlterField(
            model_name='short',
            name='phone',
            field=models.CharField(max_length=200, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd'),
        ),
    ]
